### PR TITLE
Change credit name

### PR DESCRIPTION
**Pull request by ghost**
nayuta -> NayutaWalletKit

### CODE REVIEW

**Comment by mandelmonkey** [comment]
The build falied because the tiapp.xml enc was wrong, you need to encrypt your tiapp.xml and add the nex decryption line to travis yaml

if you run ```travis encrypt_file tiapp.xml``` it will explain

```The command "if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then openssl aes-256-cbc -K $encrypted_69300d0764ac_key -iv $encrypted_69300d0764ac_iv -in tiapp.xml.enc -out tiapp.xml -d ;fi" failed and exited with 1 during .```

**Comment by ghost** [comment]
I thought fork PR can not be read TravisCI's Secure Environment Variables.

https://travis-ci.community/t/environment-variables-not-set-anymore/5085
https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions

**Comment by mandelmonkey** [comment]
hmm im not sure about environment variables but you just need to encrypt your own tiapp.xml and add the decryption line to your travis.yaml

so call ```travis encrypt-file tiapp.xml```

this will make a tiapp.xml.enc file

then you need to update the line in .travis.yaml 

```
before_install:
        - openssl aes-256-cbc -K $encrypted_979228d9d50c_key -iv $encrypted_979228d9d50c_iv -in tiapp.xml.enc -out tiapp.xml -d
```

to add the line displayed by the encryption function

**Comment by ghost** [comment]
OK!
I'll try `travis encrypt-file tiapp.xml`

**Comment by ghost** [comment]
`nayuta-kohei/NayutaWalletKit` 's travis ci is a success.
but, `NayutaWalletKit/NayutaWalletKit` 's travis ci is failed.

I tried `travis encrypt-file tiapp.xml`.
I think that the environment variable was added to the `nayuta-kohei/NayutaWalletKit`.
it was not added to the environment variable($encrypted_c7826f76e4bd_key) of `NayutaWalletKit/NayutaWalletKit`. 
So I thought it couldn't be read.

**Comment by mandelmonkey** [comment]
@nayuta-kohei I see, so you updated before install with your generated config?

``` - openssl aes-256-cbc -K $encrypted_979228d9d50c_key -iv $encrypted_979228d9d50c_iv -in tiapp.xml.enc -out tiapp.xml -d
  ```

**Comment by ghost** [comment]
@mandelmonkey 

> I see, so you updated before install with your generated config?

Is before install here?
https://github.com/NayutaWalletKit/NayutaWalletKit/blob/master/.travis.yml#L33


by the way,
How about not using tiapp.xml.enc? Because NayutaWalletKit is open source.

**Comment by mandelmonkey** [comment]
@nayuta-kohei yes thats correct, when you run travis encrypt-file is will tell you what line you need to add

hmm the problem is for other branches tiapp.xml is in gitignore, and has to be because of secret information

is it possible to have gitignore rules for each branch? so tiapp.xml is ignored in master branch but not ignored in opensrouce branch>

**Comment by mandelmonkey** [comment]
maybe we can add tiapp.xml using a different name, then in the travis build script when can change the name?

**Comment by ghost** [comment]
> maybe we can add tiapp.xml using a different name, then in the travis build script when can change the name?

good idea!

**Comment by mandelmonkey** [comment]
This is a different repo so I think it is ok to just not use travis encrypt and add the tiapp.xml

**Comment by ghost** [comment]
OK
I add tiapp.xml.

**Comment by mandelmonkey** [comment]
need to remove the line from before install as well

**Comment by ghost** [comment]
@mandelmonkey 

I added tiapp.xml.
Travis ci was a success only android.
ios was show this error.

```
[ERROR] Error: Error: The iOS class "grpcAPI" could not be found in the framework "lnGRPCWrapper". Are you trying to use "grpc" instead? (../build/iphone/build/Products/Debug-iphonesimulator/Nayuta.app/requires/lnrpc_controller.js)
```

do I  need set anything with lnGRPCWrapper?

**Comment by mandelmonkey** [comment]
hmm let me check

**Comment by mandelmonkey** [comment]
the issue is here
https://travis-ci.org/NayutaWalletKit/NayutaWalletKit/jobs/626578398#L2746
the framework is not being built, I need to check why

**Comment by mandelmonkey** [comment]
Let me take a look by tomorrow I will try to get this repo to build myself

**Comment by mandelmonkey** [comment]
@nayuta-kohei sorry for the delay but I manged to build this repo on my PR https://github.com/NayutaWalletKit/NayutaWalletKit/pull/4

I am just building again to confirm but if ok I will merge into master and you canvrebase

a few things were the issue

1. some scripts reference nayuta instead of NayutaWalletKit so it could not find some directories
2. LND mobile build has an issue with latest commit that trys to use a library that doesnt exist
3. Android build of lnd failed on ios vm, not sure why but I removed the android lndmobile build for ios vm

also we need to remove the google api ids from tiapp.xml, I will do this in a seperate PR

**Comment by ghost** [comment]
@mandelmonkey 

Build succeeded!
Thank you!

**Pull request merged**
