### PR TITLE
remove "sign out" from menu

### PR DESCRIPTION
**Pull request by nueno4**
remove "sign out" from menu (comment out)

### CODE REVIEW

**Comment by mandelmonkey** [comment]
I think sign out only shows in dev mode?

**Comment by nueno4** [comment]
Is NayutaWalletKit default setting dev mode?
I clone NayutaWalletKit and build(not change setting).

I tried to tap the menu "fully validating node", but accidentally tapped the menu "sign out".
And removed wallet data.

**Comment by mandelmonkey** [comment]
think you a building a dev version, dev version builds by default, if you build a production version it will disappear, but I will put a alert confirmation check on sign out anywy

**Comment by mandelmonkey** [comment]
oh I didnt realize that this is a different repo, then we can remove tiapp.xml.enc

**Comment by nueno4** [comment]
> I will put a alert confirmation check on sign out anywy
thank you!

**Pull request closed without merging**
